const ADMIN_NOTIFICATION_TYPES = {
  NEW_ORDER: 'NEW_ORDER',

  USER_CANCELLED_ORDER: 'USER_CANCELLED_ORDER',

  ORDER_RETURN_REQUESTED: 'ORDER_RETURN_REQUESTED',

  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',

  PAYMENT_FAILED: 'PAYMENT_FAILED',

  SYSTEM: 'SYSTEM',
}

module.exports = ADMIN_NOTIFICATION_TYPES
